# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='is_default_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitles',
            name='version_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
