# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0004_auto_20161024_1941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitles',
            unique_together=set([('video_id', 'version_name')]),
        ),
    ]
