# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0005_auto_20161029_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultVideoSubtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ytts.Video'),
        ),
        migrations.AddField(
            model_name='defaultvideosubtitles',
            name='default_subtitles_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ytts.Subtitles'),
        ),
        migrations.AddField(
            model_name='defaultvideosubtitles',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ytts.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultvideosubtitles',
            unique_together=set([('video_id', 'default_subtitles_version')]),
        ),
    ]
