# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0006_auto_20161029_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvideosubtitles',
            name='subtitles',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ytts.Subtitles', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='defaultvideosubtitles',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='defaultvideosubtitles',
            name='default_subtitles_version',
        ),
        migrations.RemoveField(
            model_name='defaultvideosubtitles',
            name='video_id',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
