# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0007_auto_20161029_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultVideoSubtitles',
            new_name='DefaultSubtitles',
        ),
    ]
