# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0008_auto_20161029_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultsubtitles',
            name='subtitles',
        ),
        migrations.DeleteModel(
            name='DefaultSubtitles',
        ),
    ]
