# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0011_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='video_tmp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ytts.Video'),
            preserve_default=False,
        ),
    ]
