# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0012_subtitles_video_tmp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitles',
            unique_together=set([('video_tmp', 'version_name')]),
        ),
    ]
