# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0013_auto_20161029_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='video_id',
        ),
    ]
