# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytts', '0014_remove_subtitles_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitles',
            old_name='video_tmp',
            new_name='video',
        ),
        migrations.AlterUniqueTogether(
            name='subtitles',
            unique_together=set([('video', 'version_name')]),
        ),
    ]
